name: API Test Automation with Allure Reports
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 'H/3 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Run Maven Tests and Generate Allure Results
        run: mvn clean test allure:report -Dmaven.test.failure.ignore=true
      - name: Load Allure Report History
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-history
      - name: Build Allure Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results_path: target/allure-results
          allure_history_path: allure-history
          allure_report_path: allure-report-output
          github_token: ${{ secrets.PAT1234}}
          skip_reporting_github_pages: true
      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.PAT1234}}
          publish_branch: gh-pages
          publish_dir: allure-report-output
          force_orphan: true
